<a href="https://colab.research.google.com/github/AbdulrahmanB-25/Apply_Compare_Clustering_Algorithms/blob/main/Evaluating_Clustering_Before_and_After_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
import zipfile
import pandas as pd
from google.colab import userdata

# It is best practice to put these in the 'Secrets' (key icon) on the left sidebar
# If you haven't done that yet, you can set them manually here:
os.environ['KAGGLE_USERNAME'] = "YOUR_KAGGLE_USERNAME" # Replace with your username
os.environ['KAGGLE_KEY'] = "KGAT_1b68b2bd8810a1b45b7141454ac48ea5"

# Download the specific dataset
!kaggle datasets download -d vjchoudhary7/customer-segmentation-tutorial-in-python

Dataset URL: https://www.kaggle.com/datasets/vjchoudhary7/customer-segmentation-tutorial-in-python
License(s): other
Downloading customer-segmentation-tutorial-in-python.zip to /content
100% 1.55k/1.55k [00:00<00:00, 2.79MB/s]

In [3]:
# 1. Unzip the file
with zipfile.ZipFile('customer-segmentation-tutorial-in-python.zip', 'r') as zip_ref:
    zip_ref.extractall('mall_data')

# 2. Load into df
# The file inside this specific dataset is named 'Mall_Customers.csv'
df = pd.read_csv('mall_data/Mall_Customers.csv')

# 3. View the data
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [6]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64